using Microsoft.CodeAnalysis;

namespace DemoGenerator;

[Generator(LanguageNames.CSharp)]
public class TestGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {// Register the attribute source
             context.RegisterPostInitializationOutput(i =>
             {
                 const string attributeSource = """
                                                
                                                     namespace AutoGenerated
                                                     {
                                                         [AttributeUsage(AttributeTargets.Class)]
                                                         public class WhoAmIAttribute : Attribute
                                                         {
                                                             public WhoAmIAttribute() { }
                                                         }
                                                     }
                                                """;

                 i.AddSource("WhoAmIAttribute.g.cs", attributeSource);
             });
    }
}